name: Lint and Test Backend and Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: cd backend && npm install

      # - name: Lint Backend
      #   run: cd backend && npm run lint

      - name: Test Backend
        run: cd backend && npm test

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      # - name: Lint Frontend
      #   run: cd frontend && npm run lint

      - name: Test Frontend
        run: cd frontend && npm test
